[package]
name = "basic"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[[bin]]
name = "basic"
path = "src/main.rs"

[dependencies]
log.workspace = true
gpui_term = { path = "../../crates/gpui_term" }
gpui-component = { path = "../../../gpui-component/crates/ui" }
gpui-component-assets = { path = "../../../gpui-component/crates/assets" }
gpui.workspace = true
portable-pty.workspace = true
smallvec = "1"
env_logger = "0.11"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26"
objc = "0.2"

